### ISSUE TITLE
Add benchmarks to README

### ISSUE THREAD

**Issue by scarroll32** [fast-jsonapi/comparisons#10]
Is it possible to add the benchmarks output to the README, perhaps with a timestamp of when it was last run?

**Comment by stas** [comment]
Hi there @seanfcarroll 

I think that would work, but it might create quite a bit of noise.
I was thinking we should integrate the benchmark as part of the Actions we run for the `jsonapi/serializer`, what do you think?

**Comment by scarroll32** [comment]
> I was thinking we should integrate the benchmark as part of the Actions we run for the jsonapi/serializer, what do you think?

That 's a great idea @stas !
